message("Looking for LibRocket")

SET(LIBROCKET_SEARCH_PATHS /usr/local ${LIBROCKET_PATH})

FIND_PATH(LIBROCKET_INCLUDE_DIR Core.h
	HINTS
	$ENV{LIBROCKETDIR}
	PATH_SUFFIXES include/Rocket include
	PATHS ${LIBROCKET_SEARCH_PATHS}
)

FIND_PATH(LIBROCKET_LIB_DIR libRocketCore.so
	HINTS
	$ENV{LIBROCKETDIR}
	PATH_SUFFIXES lib
	PATHS ${LIBROCKET_SEARCH_PATHS}
)

FIND_LIBRARY(LIBROCKET_LIBRARY_TEMP
	NAMES RocketCore
	HINTS
	$ENV{LIBROCKETDIR}
	PATH_SUFFIXES ${PATH_SUFFIXES}
	PATHS ${LIBROCKET_SEARCH_PATHS}
)