message("Looking for OpenGL")

SET(OPENGL_SEARCH_PATHS ./external /usr/local /usr/lib/* ${OPENGL_PATH})

FIND_PATH(OPENGL_INCLUDE_DIR gl.h
	HINTS
	$ENV{OPENGLDIR}
	PATH_SUFFIXES include/GL include
	PATHS ${OPENGL_SEARCH_PATHS}
)

FIND_PATH(OPENGL_LIB_DIR libGL.so
	HINTS
	$ENV{OPENGLDIR}
	PATH_SUFFIXES 
	PATHS ${OPENGL_SEARCH_PATHS}
)

FIND_LIBRARY(OPENGL_LIBRARY_TEMP
	NAMES OPENGL
	HINTS
	$ENV{OPENGLDIR}
	PATH_SUFFIXES ${PATH_SUFFIXES}
	PATHS ${OPENGL_SEARCH_PATHS}
)
