message("Looking for GLEW")

SET(GLEW_SEARCH_PATHS /usr/local ${GLEW_PATH})

FIND_PATH(GLEW_INCLUDE_DIR glew.h
	HINTS
	$ENV{GLEWDIR}
	PATH_SUFFIXES include/GL include
	PATHS ${GLEW_SEARCH_PATHS}
)

find_library(GLEW_LIBRARY
	NAMES GLEW
	HINTS
	ENV GLEWDIR
	ENV GLEWDIR
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
	PATHS ${GLEW_PATH}
)