message("Looking for SDL2_Mixer")

SET(SDL2_MIXER_SEARCH_PATHS ./external /usr/local ${SDL2_MIXER_PATH})

FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h
	HINTS
	$ENV{SDL2_MIXERDIR}
	PATH_SUFFIXES include/SDL2 include
	PATHS ${SDL2_MIXER_SEARCH_PATHS}
)

FIND_PATH(SDL2_MIXER_LIB_DIR libSDL2_mixer.a
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib
	PATHS ${SDL2_MIXER_SEARCH_PATHS}
)

find_library(SDL2_MIXER_LIBRARY
	NAMES SDL2_mixer
	HINTS
	ENV SDL2MIXERDIR
	ENV SDL2MIXERDIR
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
	PATHS ${SDL2_MIXER_PATH}
)