message("Looking for SDL2")

SET(SDL2_SEARCH_PATHS ./external /usr/local ${SDL2_PATH})

FIND_PATH(SDL2_INCLUDE_DIR SDL.h
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES include/SDL2 include
	PATHS ${SDL2_SEARCH_PATHS}
)

FIND_PATH(SDL2_LIB_DIR libSDL2.a
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib
	PATHS ${SDL2_SEARCH_PATHS}
)

FIND_LIBRARY(SDL2_LIBRARY_TEMP
	NAMES SDL2
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES ${PATH_SUFFIXES}
	PATHS ${SDL2_SEARCH_PATHS}
)
